project_id = "pofayvcrhypkcnjgkhqk"

[functions.send-invitation]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.lookup-organization]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false
