// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pofayvcrhypkcnjgkhqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZmF5dmNyaHlwa2NuamdraHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNDEwNzEsImV4cCI6MjA4ODgxNzA3MX0.dwacKXy-rQNgNhcCQM_l9lzdaWCmj0wEn0H_AhlDOC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});