// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://altwmywwfpjumzscxrjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsdHdteXd3ZnBqdW16c2N4cmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzg5NjUsImV4cCI6MjA3Mzg1NDk2NX0.a_aBh9DeOGh2nrKchXmZXj6P-K7tXlAIb121eyDnSRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});